right_format = "$time"

[character]
success_symbol = "[â†’](bold green)"
error_symbol = "[âœ•](bold red)"

[battery]
full_symbol = "ï•¸ "
charging_symbol = "ï–ƒ "
discharging_symbol = "ï•½ "
empty_symbol = "ï–‚ "
disabled = false

[[battery.display]]
threshold = 80
style = "bold red"

[time]
format = "[ï™ $time](bold red)"
time_format = "%T"
disabled = false

[shell]
powershell_indicator = "ğŸªŸ"
unknown_indicator = "mystery shell"
style = "cyan bold"
disabled = false